namespace GtfsLogging
{
    public enum LogMessageType
    {
        // GTFS processor
        ERROR_GRAPH_REPEATED_NUMBER = 1,
        ERROR_INCONSISTENT_TARRIFS = 10001,

        ERROR_ROUTE_USED_BUT_UNDEF_TRANSPORT_TYPE = 101,
        WARNING_ROUTE_UNKNOWN_TYPE = 10101,
        WARNING_ROUTE_CONFLICTED_TRIP_TYPES = 10102,
        WARNING_ROUTE_CONFLICTED_RECORDS = 10103,
        INFO_ROUTE_NO_TRIPS = 20101,

        WARNING_TRANSFER_UNKNOWN_STOP = 10201,
        WARNING_TRANSFER_UNKNOWN_LINE = 10202,

        ERROR_TRAJECTORY_UNKNOWN_STOP = 301,
        WARNING_TRAJECTORY_TOO_SHORT = 10301,

        ERROR_STOP_CONFLICTED_RECORDS = 401,
        ERROR_STOP_EMPTY_STATION = 402,
        ERROR_STOP_PARENT_NEQ_STATION = 403,
        WARNING_STOP_USED_BUT_NOT_PUBLIC = 10401,
        WARNING_STOP_USED_ZERO_COORDINATES = 10402,
        WARNING_STOP_NAME_NEQ_STATION = 10403,
        WARNING_STOP_NODE_ID_NEQ_STATION = 10404,
        WARNING_STOP_EXIT_NOT_FOUND = 10406,
        WARNING_STOP_IDS_NOT_FOUND = 10407,
        WARNING_STOP_REGION_INVALID = 10408,
        INFO_STOP_WHEELCHAIR_NEQ_STATION = 20401,
        INFO_STOP_ZONE_ID_NEQ_STATION = 20402,
        INFO_STOP_NOT_FOUND = 20405,

        ERROR_STOPTIME_MISSING_STOP = 501,
        ERROR_STOPTIME_MISSING_REMARK = 502,
        WARNING_STOPTIME_PREMATURE_ARRIVAL = 10501,
        WARNING_STOPTIME_PREMATURE_DEPARTURE = 10502,
        WARNING_STOPTIME_MISSING_STOP_VARIANT = 10503,
        INFO_STOPTIME_MISSING_STOP_VERSION = 20501,

        ERROR_UNKNOWN_TRAFFIC_TYPE = 601,
        ERROR_TRIP_WRONG_GRAPH_ID = 602,
        ERROR_TRIP_WRONG_RUN_NUM = 603,
        ERROR_TRIP_NO_STOPTIMES = 604,
        ERROR_TRIP_STARTS_WITH_UNDEF_DEPARTURE = 605,
        ERROR_TRIP_MISSING_REMARK = 605,
        ERROR_TRIP_CONFLICTED_NEXT_TRIP = 606,
        ERROR_TRIP_CALENDAR_NULL = 607,
        ERROR_TRIP_CALENDAR_WRONG = 608,
        ERROR_TRIP_DUPLICATE_UNIQUE_TRIP_ID = 609,
        ERROR_TRIP_CONFLICTED_UNIQUE_TRIP_ID = 610,
        ERROR_TRIP_NEXT_TRIP_TOO_SOON_DEPARTURE = 611,
        ERROR_TRIP_BLOCK_INCOMPATIBLE = 612,
        WARNING_TRIP_ROUTE_MISSING = 10601,
        WARNING_TRIP_ROUTE_MISSING_ADDED = 10602,
        WARNING_TRIP_NULL_VEHICLE_TYPE = 10603,
        WARNING_TRIP_UNKNOWN_VEHICLE_TYPE = 10604,
        WARNING_TRIP_MISSING_ROUTE_VERSION = 10605,
        WARNING_TRIP_STARTS_BEFORE_3AM = 10606,
        WARNING_TRIP_PREMATURE_DEPARTURE = 10607,
        WARNING_TRIP_CALENDAR_NOT_SUBSET_OF_SEQUENCE = 10608,
        WARNING_TRIP_CALENDAR_NOT_SUBSET_OF_GRAPH = 10609,
        WARNING_TRIP_MISSING_NEXT_TRIP = 10610,
        WARNING_TRIP_IRREGULAR_NOT_TRAM = 10611,
        WARNING_TRIP_TO_DEPO_CONTINUES_DIFFERENTLY = 10612,
        WARNING_TRIP_FROM_DEPO_STARTS_DIFFERENTLY = 10613,
        WARNING_TRIP_NEXT_TRIP_TOO_SOON_ARRIVAL = 10614,
        WARNING_TRIP_BLOCK_STOPS_DO_NOT_MATCH = 10615,

        ERROR_VEHICLE_TYPE_DUPLICATE_AMBIGUOUS = 701,

        WARNING_REMARK_DUPLICATE = 10801,
        WARNING_REMARK_MISSING_LINE = 10802,
        WARNING_REMARK_MISSING_LINE_VERSION = 10803,

        ERROR_SHAPE_EQ_TRIPS_WITH_DIFFERENT_STOP_TIMES = 10901,

        ERROR_METRO_ENTRANCE_DUPLICATE_ID = 1001,
        WARNING_METRO_ENTRANCE_NO_MATCH = 11001,

        ERROR_MISSING_AGENCY = 1101,

        // Stop processor
        ERROR_STOP_MISSING_IN_GTFS = 3001,
        ERROR_STOP_WRONG_GTFS_ID = 3002,
        ERROR_ROUTE_WRONG_GTFS_ID = 3003,
        ERROR_STOP_ZERO_COORDINATES = 3004,
        WARNING_STOP_ZERO_CIS = 13001,
        WARNING_STOP_GROUP_CONFLICTED_TRAIN_FLAG = 13002,
        WARNING_STOP_GROUP_TRAIN_FLAG_BAD_IDOS_CATEGORY = 13003,
        WARNING_STOP_GROUP_MISSING_DISTRICT_CODE = 13004,
        WARNING_STOP_GROUPS_CONFLICTED_CIS_ID = 13005,
        WARNING_STOP_GROUPS_CONFLICTED_NAME = 13006,
        WARNING_STOP_GROUPS_CONFLICTED_UNIQUE_NAME = 13007,
        WARNING_STOP_GROUPS_INCONSISTENT = 13008,
        INFO_STOP_DUPLICATE = 23001,
        INFO_STOP_FULL_NAME_CONTAINS_ABBREVS = 23002,
        INFO_STOP_GROUP_NOT_REPRESENTED = 23003,

        // Train timetables processor
        WARNING_TRAIN_MSG_UNDEF_TIMING = 13101,
        WARNING_TRAIN_MSG_MISSING_CALENDAR = 13102,
        WARNING_TRAIN_MSG_FUTURE_SERVICE = 13103,
        WARNING_TRAIN_MSG_CALENDAR_ENDS_TOO_SOON = 13104,
        WARNING_TRAIN_DUPLICATE_ID = 13105,

        WARNING_TRAIN_STOP_CONFLICT = 13110,
        WARNING_TRAIN_STOP_REWRITE_NOT_APPLIED = 13111,
        WARNING_TRAIN_OPERATOR_DUPLICATE = 13114,
        WARNING_TRAIN_LINE_DUPLICATE = 13115,
        WARNING_TRAIN_MISSING_STOP = 13116,
        WARNING_TRAIN_MISSING_STOP_IN_ASW = 13117,
        WARNING_TRAIN_SHAPE_PATH_NOT_FOUND = 13120,
        WARNING_TRAIN_SHAPE_TOO_FAR_FROM_STOP = 13121,
        WARNING_TRAIN_NO_SHAPE_AROUND = 13122,
        WARNING_TRAIN_STOP_ZERO_COORDINATES = 13123,

        INFO_TRAIN_ONE_OPPOSITE_STOP_DIRECTION = 23101,
        INFO_TRAIN_MANY_OPPOSITE_STOP_DIRECTION = 23102,
    }

    public static class LogMessageTypeHelper
    {
        public static bool IsError(LogMessageType messageType)
        {
            return (int)messageType < 10000;
        }
    }
}
